services:
  flaskbb:
    image: flaskbb:plugins
    build:
      context: .
      dockerfile: Dockerfile.plugin
      args:
        FLASKBB_IMAGE: ${FLASKBB_IMAGE:-ghcr.io/flaskbb/flaskbb:latest}
        FLASKBB_PLUGINS: ${FLASKBB_PLUGINS:-}

  celery:
    image: flaskbb:plugins
