"""Add account activation timestamp

Revision ID: 0ece7c8bfb07
Revises: 10879048c708
Create Date: 2016-04-25 22:38:44.504224

"""

# revision identifiers, used by Alembic.
revision = '0ece7c8bfb07'
down_revision = '10879048c708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activated')
    ### end Alembic commands ###
