"""Login attempts

Revision ID: 10879048c708
Revises: 127be3fb000
Create Date: 2016-03-07 17:27:37.159830

"""

# revision identifiers, used by Alembic.
revision = '10879048c708'
down_revision = '127be3fb000'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'last_failed_login')
    ### end Alembic commands ###
