"""roles

Revision ID: 537b84ff7327
Revises: 127be3fb000
Create Date: 2015-05-19 11:25:25.131206

"""

# revision identifiers, used by Alembic.
revision = '537b84ff7327'
down_revision = '127be3fb000'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_groups',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.drop_column('groups', 'editpost')
    op.drop_column('groups', 'postreply')
    op.drop_column('groups', 'guest')
    op.drop_column('groups', 'admin')
    op.drop_column('groups', 'banned')
    op.drop_column('groups', 'mod_banuser')
    op.drop_column('groups', 'posttopic')
    op.drop_column('groups', 'deletetopic')
    op.drop_column('groups', 'super_mod')
    op.drop_column('groups', 'mod')
    op.drop_column('groups', 'mod_edituser')
    op.drop_column('groups', 'deletepost')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('deletepost', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('mod_edituser', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('mod', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('super_mod', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('deletetopic', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('posttopic', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('mod_banuser', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('banned', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('admin', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('guest', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('postreply', sa.BOOLEAN(), nullable=False))
    op.add_column('groups', sa.Column('editpost', sa.BOOLEAN(), nullable=False))
    op.drop_table('roles_groups')
    op.drop_table('roles')
    ### end Alembic commands ###
