"""Add account active state

Revision ID: 94b3d7958114
Revises: 10879048c708
Create Date: 2016-04-29 20:40:26.762939

"""

# revision identifiers, used by Alembic.
revision = '94b3d7958114'
down_revision = '10879048c708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activated')
    ### end Alembic commands ###
