"""add default group

Revision ID: ecc14a7aaa75
Revises: eddcabd0baee
Create Date: 2016-06-23 17:57:05.309697

"""

# revision identifiers, used by Alembic.
revision = 'ecc14a7aaa75'
down_revision = 'eddcabd0baee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('default_group', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'default_group')
    ### end Alembic commands ###
