"""Add cascades

Revision ID: af3f5579c84d
Revises: 7c3fcf8a3335
Create Date: 2018-02-02 10:27:50.290095

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af3f5579c84d"
down_revision = "7c3fcf8a3335"
branch_labels = ()
depends_on = None


def drop_foreign_keys(batch_op, inspector, table_name, *columns):
    # The existing foreign keys are named differently depending on how the
    # database was created: naming convention names when it was built by
    # these migrations, dialect defaults (conversations_user_id_fkey,
    # conversations_ibfk_1) for installs from before 2018. Match by column.
    for foreign_key in inspector.get_foreign_keys(table_name):
        constrained = foreign_key["constrained_columns"]
        if foreign_key["name"] and len(constrained) == 1 and constrained[0] in columns:
            batch_op.drop_constraint(foreign_key["name"], type_="foreignkey")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        drop_foreign_keys(
            batch_op, inspector, "conversations", "user_id", "from_user_id", "to_user_id"
        )

        batch_op.create_foreign_key(
            batch_op.f("fk_conversations_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_conversations_from_user_id_users"),
            "users",
            ["from_user_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_conversations_to_user_id_users"),
            "users",
            ["to_user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("forumgroups", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "forumgroups", "group_id", "forum_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_forumgroups_group_id_groups"),
            "groups",
            ["group_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_forumgroups_forum_id_forums"),
            "forums",
            ["forum_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("forums", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "forums", "category_id", "last_post_user_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_forums_category_id_categories"),
            "categories",
            ["category_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_forums_last_post_user_id_users"),
            "users",
            ["last_post_user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("forumsread", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "forumsread", "forum_id", "user_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_forumsread_forum_id_forums"),
            "forums",
            ["forum_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_forumsread_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("groups_users", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "groups_users", "user_id", "group_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_groups_users_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_groups_users_group_id_groups"),
            "groups",
            ["group_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

        drop_foreign_keys(batch_op, inspector, "messages", "conversation_id", "user_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_messages_conversation_id_conversations"),
            "conversations",
            ["conversation_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_messages_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("moderators", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "moderators", "forum_id", "user_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_moderators_forum_id_forums"),
            "forums",
            ["forum_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_moderators_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("plugin_store", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "plugin_store", "plugin_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_store_plugin_id_plugin_registry"),
            "plugin_registry",
            ["plugin_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "posts", "topic_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_posts_topic_id_topics"),
            "topics",
            ["topic_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("settings", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "settings", "settingsgroup")

        batch_op.create_foreign_key(
            batch_op.f("fk_settings_settingsgroup_settingsgroup"),
            "settingsgroup",
            ["settingsgroup"],
            ["key"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("topics", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "topics", "forum_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_topics_forum_id_forums"),
            "forums",
            ["forum_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("topicsread", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "topicsread", "topic_id", "forum_id", "user_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_topicsread_topic_id_topics"),
            "topics",
            ["topic_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_topicsread_forum_id_forums"),
            "forums",
            ["forum_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_topicsread_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("topictracker", schema=None) as batch_op:
        drop_foreign_keys(batch_op, inspector, "topictracker", "topic_id", "user_id")

        batch_op.create_foreign_key(
            batch_op.f("fk_topictracker_topic_id_topics"),
            "topics",
            ["topic_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_topictracker_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topictracker", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_topictracker_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_topictracker_topic_id_topics"), type_="foreignkey")
        batch_op.create_foreign_key("fk_topictracker_user_id_users", "users", ["user_id"], ["id"])

    with op.batch_alter_table("topicsread", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_topicsread_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_topicsread_forum_id_forums"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_topicsread_topic_id_topics"), type_="foreignkey")
        batch_op.create_foreign_key("fk_topicsread_user_id_users", "users", ["user_id"], ["id"])

    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_topics_forum_id_forums"), type_="foreignkey")

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_settings_settingsgroup_settingsgroup"), type_="foreignkey"
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_posts_topic_id_topics"), type_="foreignkey")

    with op.batch_alter_table("plugin_store", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_plugin_store_plugin_id_plugin_registry"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_plugin_store_plugin_id_plugin_registry",
            "plugin_registry",
            ["plugin_id"],
            ["id"],
        )

    with op.batch_alter_table("moderators", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_moderators_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_moderators_forum_id_forums"), type_="foreignkey")
        batch_op.create_foreign_key("fk_moderators_user_id_users", "users", ["user_id"], ["id"])

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_messages_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(
            batch_op.f("fk_messages_conversation_id_conversations"), type_="foreignkey"
        )

        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)

        batch_op.create_foreign_key("fk_messages_user_id_users", "users", ["user_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_messages_conversation_id_conversations",
            "conversations",
            ["conversation_id"],
            ["id"],
        )

    with op.batch_alter_table("groups_users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_groups_users_group_id_groups"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_groups_users_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key("fk_groups_users_user_id_users", "users", ["user_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_groups_users_group_id_groups", "groups", ["group_id"], ["id"]
        )

    with op.batch_alter_table("forumsread", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_forumsread_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_forumsread_forum_id_forums"), type_="foreignkey")
        batch_op.create_foreign_key("fk_forumsread_user_id_users", "users", ["user_id"], ["id"])

    with op.batch_alter_table("forums", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_forums_last_post_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("fk_forums_category_id_categories"), type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_forums_last_post_user_id_users", "users", ["last_post_user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_forums_category_id_categories", "categories", ["category_id"], ["id"]
        )

    with op.batch_alter_table("forumgroups", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_forumgroups_forum_id_forums"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_forumgroups_group_id_groups"), type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_forumgroups_group_id_groups", "groups", ["group_id"], ["id"]
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_conversations_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key("fk_conversations_user_id_users", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###
