User Documentation
~~~~~~~~~~~~~~~~~~

.. toctree::
   :maxdepth: 1

   development/setup
   production/deployment
   cli
   plugins/index
   faq
   releases


Developer Documentation
~~~~~~~~~~~~~~~~~~~~~~~

.. toctree::
   :maxdepth: 1

   development/theming
   development/localization
   development/hooks/index
   development/plugin/index
   development/api/index
   development/settings


Additional Information
~~~~~~~~~~~~~~~~~~~~~~

.. toctree::
   :maxdepth: 2

   changelog
   license

* :ref:`search`
